image: Visual Studio 2017

platform:
    - x64

cache:
    - node_modules

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 10 x64
    - npm install -g esy
    - npm install

build_script:
    - npm run build
    - npm test
    # Validate binary
    - _esy\build\install\default\bin\gentype.native.exe --help
    - tar czvf gentype-4.06-win.tar.gz -C _esy\build\install\default\bin gentype.native.exe

artifacts:
    - path: gentype-4.06-win.tar.gz
      name: Windows Build
      type: File

deploy:
    - provider: GitHub
      repository: cristianoc/genType
      auth_token:
        secure: h4ts/g/OSbN7Ol71eZWP2EXFvPaHaizMj3gpaAl7An4vO/2dYATb+r3PHcWD6nFp
      draft: false
      artifact: gentype-4.06-win.tar.gz
      force_update: true
      on:
        appveyor_repo_tag: true
